### ISSUE TITLE
Choosing an Embedding Model

### ISSUE THREAD

**Issue by fearnworks** [HSV-AI/presentations#94]
# Complete the following items to get a presentation ready for Huntsville AI

- [x] Description Completed
- [x] Image Attached
- [x] HSV.AI Event Created - [hsv.ai](https://hsv.ai/events)
- [x] Facebook Event Created - [Facebook Group](https://www.facebook.com/groups/hsvai/)
- [x] LinkedIn Event Created - [Huntsville AI](https://www.linkedin.com/company/huntsville-ai)

# Adding material to the presentations repository

Add the file to present (prefer Jupyter Notebooks or Markdown formated files) to the folder structure. For multiple files, create a directory following the naming convention and add the files to it.

## Naming convention

We use a convention of starting the filenames with a date (year/month/day) so that the files are still sorted by date even when in alphabetical format.

YYMMDD_Session_Description.extension

**Comment by fearnworks** [comment]
https://github.com/HSV-AI/presentations/pull/96

**Comment by jperiodlangley** [comment]
From the pull request #96 

A presentation on how to evaluate the right embedding model for your project utilizing the MTEB leaderboard as a guide.

# Description :
Join us as we explore the crucial task of selecting optimal embedding models to enhance AI performance across a variety of applications. This meetup will delve into the Multilingual Transferable Embedding Benchmark (MTEB), a pivotal resource providing a comprehensive framework to evaluate embedding models over diverse task categories and numerous languages. The selection of the right embedding model is vital, yet challenging due to the myriad of options and their inherent trade-offs. This presentation will not only introduce you to MTEB’s holistic approach across eight core NLP tasks but will also guide you through the practical steps of identifying, shortlisting, and benchmarking models to find the best fit for your specific needs.

# Agenda:

- Introduction to Embedding Models - Gain insights into why choosing the right model is critical for AI tasks.
- Overview of MTEB - Understand the framework of the Multilingual Transferable Embedding Benchmark and its application across 100+ languages.
- Deep Dive into MTEB Tasks - Explore the eight fundamental tasks within MTEB, including bitext mining, classification, clustering, and more.
- Case Studies - Walk through real-world use cases, demonstrating how to apply MTEB in selecting models for tasks such as walking path recommendations, form filling automation, and building a documentation assistant.

**Comment by jperiodlangley** [comment]
We can go with this, unless you have something already:

![Choosing an Embedding Model](https://github.com/HSV-AI/presentations/assets/6886690/6d6f1e6f-60f2-409a-9f82-21b8cc9017c5)

**Comment by fearnworks** [comment]
Works for me!
